menu:
    Blog: /blog/
    Profile: /blog/profile/
    Archive: /blog/archives/
    Twitter: https://twitter.com/melo15
    GitHub: https://github.com/NaokiOtsu

favicon: /favicon.png
logo: /blog/images/logo.png

# Comment
# e.g disqus: seansun
disqus: naokiotsu
duoshuo:

# Analytics
# google-analytics:
ga: UA-7365476-10

# Copyright Infomation
startyear: 2016
